### ISSUE TITLE
Converting ultisnips snippets to luasnip

### ISSUE THREAD

**Issue by medwatt** [evesdropper/dotfiles#3]
Hey. I contact you about a week ago regarding how to do visual mode in luasnip. I am writing a basic parser that can convert ultisnips snippets to luasnip. At the moment, it can do basic conversions. You can find it [here](https://github.com/medwatt/ultisnips_to_luasnip). I thought since you are familiar with the syntax of luasnip, you might be able to help. You don't have to worry about parsing or anything. That has already been done. I just need some help in those cases where we need to use dynamic nodes, function nodes, etc. Of course, its not going to be possible to convert everything. The goal is, to get the snippet converted as much as possible and leave the other parts for the user to clean up. Let me know what you think.

**Comment by evesdropper** [comment]
I could try to answer any questions you may have. Generally, dynamic corresponds to pre-expands and function to python interpolation.

That being said, I would suggest that one learns how to use LuaSnip vs using a converter except for mundane tasks like text/insert node heavy snippets.
